name: CI - Build & Test

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@v6

    - name: Test with python ${{ matrix.python-version }}
      env:
        CORR_REDIS_URL: "test"
      run: |
        uv run --frozen coverage run -m pytest
        uv run coverage report
        uv run coverage xml

    - name: Upload coverage to GitHub summary
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml

    - name: Build wheel
      run: |
        pip install build
        python -m build

    - name: Upload dist artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: dist/